config/routes.rb
Rails.application.routes.draw do
	# User
	resources :users, only: [:index, :new, :create]
	resources :user_sessions, only: [:create, :destroy]
	resources :password_resets, only: [:new, :create, :edit, :update]
	delete "/sign_out", to: "user_sessions#destroy", as: :sign_out
	get "/sign_in", to: "user_sessions#new", as: :sign_in
	#/User

	# Blog
	post "/blog/all/search", to: "blog#all", as: "search_all"
	get "/blog/all/search", to: "blog#all"
	get "/blog/all", to: "blog#all", as: "all_blog"
	get "/blog/all/:id/read", to: "blog#read", as: "read_blog"
	
	resources :blog do
		resources :comments
	end
	
	post "/blog/search", to: "blog#index", as: "search_blog"
	get "/blog", to: "blog#index", as: "blags"
	get "/blog/:id", to: "blog#update", as: "blag"
	get "/blog", to: "blog#index"
	get "/blog/:id/edit", to: "blog#edit", as: "edit_blag"
	
	get "/blog/:blag_id/comments", to: "comments#index", as: "blag_comments"
	post "/blog/:blag_id/comments", to: "comments#create"
	get "/blog/:blag_id/comments/new", to: "comments#new", as: "new_blag_comment"
	get "/blog/:blag_id/comments/:id/edit", to: "comments#edit", as: "edit_blag_comment"
	get "/blog/:blag_id/comments/:id", to: "comments#show", as: "blag_comment"
	patch "/blog/:blag_id/comments/:id", to: "comments#update"
	put "/blog/:blag_id/comments/:id", to: "comments#update"
	delete "/blog/:blag_id/comments/:id", to: "comments#destroy"
	#/Blog

	# Blog API
	namespace :api, path: "/v1", defaults: { format: :json, constraints: { subdomain: "api" } } do
		resources :blog, only: [:index, :show] do
			resources :comments
		end
	end
	#/Blog API
	
	root "welcome#index"
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
	skip_before_action :require_login
	
	private def password_reset_params
		params.require(:user).permit(:password, :password_confirmation)
	end
	
	def new
	end
	
	def create
		@user = User.find_by_email(params[:email])
		email = params[:email]
		email = " <strong>"+ email +"</strong>" if !email.blank?
		if !@user
			respond_to do |format|
				flash[:danger] = "Unable to continue forgot password because email"+ email +" not found."
				format.html { redirect_to new_password_reset_path and return }
				format.json { render json: flash[:danger], status: :unprocessable_entity }
			end
		end
		respond_to do |format|
			if @user.deliver_password_reset_instructions!
				flash[:success] = "Instructions to reset your password has been sent to"+ email +". If you can find it in your Inbox, kindly check it in your Spam or Junk folder. Thank you!"
				format.html { redirect_to root_path }
				format.json { render :show, status: :created, location: root_path }
			else
				flash[:danger] = "Unable to continue forgot password for"+ email +" because "+ @user.errors.to_a.join(", ") +"."
				format.html { redirect_to new_password_reset_path }
				format.json { render json: @user.errors, status: :unprocessable_entity }
			end
		end
	end
	
	def edit
		@user = User.find_by(perishable_token: params[:id])
		if !@user
			respond_to do |format|
				flash[:danger] = "Unable to reset password due to invalid token."
				format.html { render :edit }
				format.json { render json: flash[:danger], status: :unprocessable_entity }
			end
		end
	end
	
	def update
		@user = User.find_by(perishable_token: params[:id], email: params[:email])
		if !@user
			respond_to do |format|
				flash[:danger] = "Unable to reset password because token and email <strong>"+ params[:email].to_s() +"</strong> not matched."
				format.html { redirect_to edit_password_reset_path(params[:id]) and return }
				format.json { render json: flash[:danger], status: :unprocessable_entity }
			end
		end
		
		transact = @user.update_attributes(password_reset_params)
		email = @user.email.to_s()
		email = " <strong>"+ email +"</strong>" if !email.blank?
		respond_to do |format|
			if transact
				flash[:success] = "Reset Password for"+ email +" successful."
				format.html { redirect_to root_path }
				format.json { render :show, status: :ok, location: root_path }
				current_user_session.destroy
			else
				flash[:danger] = "Unable to reset password for"+ email +" because "+ @user.errors.to_a.join(", ") +"."
				format.html { render :edit }
				format.json { render json: @user.errors, status: :unprocessable_entity }
			end
		end
	end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<div class="col-sm-offset-4 col-sm-4">
	<div class="panel panel-danger">
		<div class="panel-heading"><h1 class="panel-title text-center">Reset Password</h1></div>
		<div class="panel-body">
		<% if @user %>
			<%= form_tag password_reset_path(params[:id]), name: "user", class: "form-horizontal", method: :put do -%>
				<div class="field form-group">
					<%= label_tag "password", nil, class: "control-label sr-only" %>
					<div class="col-sm-12">
					<%= password_field_tag "password", nil, class: "form-control", placeholder: "Password", required: "true", title: "Password", "data-toggle": "tooltip", "data-placement": "left", autofocus: true, name: "user[password]" %>
					</div>
				</div>
				<div class="field form-group">
					<%= label_tag "password_confirmation", nil, class: "control-label sr-only" %>
					<div class="col-sm-12">
					<%= password_field_tag "password_confirmation", nil, class: "form-control", placeholder: "Password Confirmation", required: "true", title: "Password Confirmation", "data-toggle": "tooltip", "data-placement": "left", name: "user[password_confirmation]" %>
					</div>
				</div>
				<div class="field form-group">
					<%= label_tag "email", nil, class: "control-label sr-only" %>
					<div class="col-sm-12">
					<%= email_field_tag "email", nil, class: "form-control", placeholder: "Email", required: "true", title: "Email Address", "data-toggle": "tooltip", "data-placement": "left" %>
					<h5 class="text-muted">For security purposes, kindly enter your email address.</h5>
					</div>
				</div>
				<div class="actions form-group">
					<h7>&nbsp;</h7>
					<div class="col-sm-12 text-center">
					<%= submit_tag "Submit", class: "btn btn-danger", title: "Submit Reset Password", "data-toggle": "tooltip", "data-placement": "bottom" %>
					<%= button_tag "Clear", type: "reset", class: "btn btn-default", title: "Clear Above Field", "data-toggle": "tooltip", "data-placement": "bottom" %>
					</div>
				</div>
			<% end -%>
		<% end %>
		</div>
	</div>
</div>

app/views/password_resets/new.html.erb
<div class="col-sm-offset-4 col-sm-4">
	<div class="panel panel-default">
		<div class="panel-heading"><h1 class="panel-title text-center">Forgot Password</h1></div>
		<div class="panel-body">
			<%= form_tag password_resets_path, class: "form-horizontal" do -%>
				<div class="field form-group">
					<%= label_tag :email, nil, class: "control-label sr-only" %>
					<div class="col-sm-12">
					<%= email_field_tag :email, nil, class: "form-control", placeholder: "Email", required: "true", title: "Email Address", "data-toggle": "tooltip", "data-placement": "left", autofocus: true %>
					</div>
				</div>
				<div class="actions form-group">
					<h7>&nbsp;</h7>
					<div class="col-sm-12 text-center">
					<%= submit_tag "Submit", class: "btn", title: "Submit Forgot Password", "data-toggle": "tooltip", "data-placement": "bottom" %>
					<%= button_tag "Clear", type: "reset", class: "btn btn-default", title: "Clear Above Field", "data-toggle": "tooltip", "data-placement": "bottom" %>
					</div>
				</div>
			<% end -%>
		</div>
	</div>
</div>