config/routes.rb
Rails.application.routes.draw do
	# User
	resources :users, only: [:index, :new, :create]
	resources :user_sessions, only: [:create, :destroy]
	resources :password_resets, only: [:new, :create, :edit, :update]
	delete "/sign_out", to: "user_sessions#destroy", as: :sign_out
	get "/sign_in", to: "user_sessions#new", as: :sign_in
	#/User

	# Blog
	post "/blog/all/search", to: "blog#all", as: "search_all"
	get "/blog/all/search", to: "blog#all"
	get "/blog/all", to: "blog#all", as: "all_blog"
	get "/blog/all/:id/read", to: "blog#read", as: "read_blog"
	
	resources :blog do
		resources :comments
	end
	
	post "/blog/search", to: "blog#index", as: "search_blog"
	get "/blog", to: "blog#index", as: "blags"
	get "/blog/:id", to: "blog#update", as: "blag"
	get "/blog", to: "blog#index"
	get "/blog/:id/edit", to: "blog#edit", as: "edit_blag"
	
	get "/blog/:blag_id/comments", to: "comments#index", as: "blag_comments"
	post "/blog/:blag_id/comments", to: "comments#create"
	get "/blog/:blag_id/comments/new", to: "comments#new", as: "new_blag_comment"
	get "/blog/:blag_id/comments/:id/edit", to: "comments#edit", as: "edit_blag_comment"
	get "/blog/:blag_id/comments/:id", to: "comments#show", as: "blag_comment"
	patch "/blog/:blag_id/comments/:id", to: "comments#update"
	put "/blog/:blag_id/comments/:id", to: "comments#update"
	delete "/blog/:blag_id/comments/:id", to: "comments#destroy"
	#/Blog

	# Blog API
	namespace :api, path: "/v1", defaults: { format: :json, constraints: { subdomain: "api" } } do
		resources :blog, only: [:index, :show] do
			resources :comments
		end
	end
	#/Blog API
	
	root "welcome#index"
end

app/controllers/api/blog_controller.rb
module API
	class BlogController < ApplicationController
		skip_before_action :require_login
		
		def index
			search = params[:search]
			blog = Blag.created_asc
			blog = blog.search_blog(search) if search
			blog = blog.reverse
			render json: blog
		end
		
		def show
			blog = Blag.find(params[:id])
			render json: blog if stale?(last_modified: blog.updated_at, public: true)
		rescue
			render json: blog
		end
	end
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
	before_filter :get_user, except: [ :all, :read ]

	private def blog_params
		params.require(:blag).permit(:title, :contents) unless params[:search]
	end
	
	def get_user
		@user = User.find(current_user)
	end

	def index
		search = params[:search]
		if search
			@blog = @user.blags.search_blog(search).created_asc
		else
			@blog = @user.blags.created_asc
		end
		if @blog.blank?
			respond_to do |format|
				flash[:danger] = (search ? "No blog with <strong>"+ params[:search].to_s() +"</strong> found" : "No blog to be searched yet! Get started &raquo; "+ '<a href="'+ new_blog_path.to_s() +'" title="Create New" data-toggle="tooltip" data-placement="bottom"><span class="glyphicon glyphicon-plus-sign"></span><span class="sr-only">Create</span></a>')
				format.html # index.html.erb
				format.json { render json: flash[:danger], status: :unprocessable_entity }
			end
			@no_blog_found = flash[:danger]
		end
		flash[:success] = "<u>"+ @blog.length.to_s() +"</u> blog".pluralize(@blog.length) +" found with <strong>"+ params[:search].to_s() +"</strong>" if search && @blog.length > 0
		@blog = @blog.reverse
	end
	
	def show
		@blog = @user.blags.find(params[:id])
	end
	
	def all
		search = params[:search]
		if search
			@blog = Blag.blogs.search_blog(search, true).created_asc
		else
			@blog = Blag.blogs.created_asc
		end
		if @blog.blank?
			respond_to do |format|
				flash[:danger] = (search ? "No blog with <strong>"+ params[:search].to_s() +"</strong> found" : "No blog to be searched yet! Get started &raquo; "+ '<a href="'+ new_blog_path.to_s() +'" title="Create New" data-toggle="tooltip" data-placement="bottom"><span class="glyphicon glyphicon-plus-sign"></span><span class="sr-only">Create</span></a>')
				format.html # index.html.erb
				format.json { render json: flash[:danger], status: :unprocessable_entity }
			end
			@no_blog_found = flash[:danger]
		end
		flash[:success] = "<u>"+ @blog.length.to_s() +"</u> blog".pluralize(@blog.length) +" found with <strong>"+ params[:search].to_s() +"</strong>" if search && @blog.length > 0
		@blog = @blog.reverse
	end
	
	def read
		@blog = Blag.blogs.find(params[:id])
	end
	
	def new
		@blog = @user.blags.new
		keep_url_referrer
	end
	
	def edit
		@blog = @user.blags.find(params[:id])
		keep_url_referrer
	end
	
	def create
		@blog = @user.blags.create(blog_params)
		transact = @blog.save
		title = @blog.title.to_s()
		title = "<strong>"+ title +"</strong> " if !title.blank?
		respond_to do |format|
			if transact
				flash[:success] = title +"successfully created."
				format.html { redirect_to url_referrer }
				format.json { render :show, status: :created, location: url_referrer }
			else
				flash[:danger] = "Unable to save "+ title +"due to "+ @blog.errors.to_a.join(", ") +"."
				format.html { render :new }
				format.json { render json: @blog.errors, status: :unprocessable_entity }
			end
		end
	end
	
	def update
		@blog = @user.blags.find(params[:id])
		transact = @blog.update(blog_params)
		title = @blog.title.to_s()
		title = "<strong>"+ title +"</strong> " if !title.blank?
		respond_to do |format|
			if transact
				flash[:success] = title +"successfully updated."
				format.html { redirect_to url_referrer }
				format.json { render :show, status: :ok, location: url_referrer }
			else
				flash[:danger] = "Unable to update "+ title +"due to "+ @blog.errors.to_a.join(", ") +"."
				format.html { render :edit }
				format.json { render json: @blog.errors, status: :unprocessable_entity }
			end
		end
	end
	
	def destroy
		keep_url_referrer
		@blog = @user.blags.find(params[:id])
		transact = @blog.destroy
		title = @blog.title.to_s()
		title = "<strong>"+ title +"</strong> " if !title.blank?
		respond_to do |format|
			if transact
				flash[:success] = title +"successfully deleted."
				format.html { redirect_to url_referrer }
				format.json { render :show, status: :ok, location: url_referrer }
			else
				flash[:danger] = "Unable to delete "+ title +"due to "+ @blog.errors.to_a.join(", ") +"."
				format.html { render :edit }
				format.json { render json: @blog.errors, status: :unprocessable_entity }
			end
		end
	end
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/views/blog/_blog.html.erb
<%
cntBlog = 0
@blog.each do |b|
	cntBlog += 1
	title = b.title
	created = b.created_at.strftime("%m/%e/%Y at %I:%M %p")
%>
<h3>
	<sup><small><%= cntBlog %></small></sup>
	<%= b.title %>
	<small><small class="muted" data-toggle="tooltip" data-placement="bottom" title="<%= title %> has been created on <%= created %>"><%= created %></small></small>
	<small class="pull-right">
		<%= link_to '<span class="glyphicon glyphicon-eye-open"></span><span class="sr-only">Read</span>'.html_safe, b, title: 'Read', "data-toggle": "tooltip", "data-placement": "bottom" %>
		<%= link_to '<span class="glyphicon glyphicon-plus-sign"></span><span class="sr-only">Create</span>'.html_safe, new_blog_path, title: 'Create', "data-toggle": "tooltip", "data-placement": "bottom"  %>
		<%= link_to '<span class="glyphicon glyphicon-edit"></span><span class="sr-only">Update</span>'.html_safe, edit_blog_path(b), title: 'Update', "data-toggle": "tooltip", "data-placement": "bottom" %>
		<%= link_to '<span class="glyphicon glyphicon-remove-sign"></span><span class="sr-only">Delete</span></a>'.html_safe, b, method: :delete, data: { confirm: "Do you really want to delete #{title}?" }, title: 'Delete', "data-toggle": "tooltip", "data-placement": "bottom" %>
	</small>
</h3>
<blockquote>
	<p data-toggle="popover" data-placement="top" data-content="Click the Eye icon to read more about <%= b.title %>"><%= strip_tags(b.contents).first(80) + (strip_tags(b.contents).length > 80 ? "..." : "") %></p>
</blockquote>
<%= '<div class="divider"><hr /></div>'.html_safe if !@blog.count.eql?cntBlog %>
<% end %>

app/views/blog/_formBlog.html.erb
<%= form_for @user, html: {class:"form-horizontal"} do |f| %>
	<div class="row">
		<div class="small-4 columns">
		<%= f.label :first_name, for: :first_name %>
		</div>
		<div class="small-8 columns">
		<%= f.text_field :first_name, placeholder: "First Name", required: true %>
		</div>
	</div>
	<div class="row">
		<div class="small-4 columns">
		<%= f.label :middle_name, for: :middle_name %>
		</div>
		<div class="small-8 columns">
		<%= f.text_field :middle_name, placeholder: "Middle Name" %>
		</div>
	</div>
	<div class="row">
		<div class="small-4 columns">
		<%= f.label :last_name, for: :last_name %>
		</div>
		<div class="small-8 columns">
		<%= f.text_field :last_name, placeholder: "Last Name", required: true %>
		</div>
	</div>
	<div class="row">
		<div class="small-4 columns">
		<%= f.label :email, for: :email %>
		</div>
		<div class="small-8 columns">
		<%= f.email_field :email, placeholder: "Email Address", required: true %>
		</div>
	</div>
	<div class="row">
		<div class="small-4 columns">
		<%= f.label :password, for: :password %>
		</div>
		<div class="small-8 columns">
		<%= f.password_field :password, placeholder: "Password", required: true %>
		</div>
	</div>
	<div class="row">
		<div class="small-4 columns">
		<%= f.label :password_confirmation, for: :password_confirmation %>
		</div>
		<div class="small-8 columns">
		<%= f.password_field :password_confirmation, placeholder: "Password Confirmation", required: true %>
		</div>
	</div>
	<div class="row actions">
		<div class="small-12 columns">
		<%= f.submit :Save, class: "button" %>
		<%= f.button :Clear, type: "reset", class: "button secondary" %>
		</div>
	</div>
<% end %>

app/views/blog/all.html.erb
<div class="panel panel-default">
	<div class="panel-body">
	<%
	cntBlog = 0
	@blog.each do |b|
		cntBlog += 1
		title = b.title
		created = b.created_at.strftime("%m/%e/%Y at %I:%M %p")
		author = b.author.split("@").first.to_s()
	%>
		<sup><%= cntBlog %></sup>
		<%= link_to "<h4>#{b.title}</h4>".html_safe, read_blog_path(b), class: "btn btn-link", role: "button", title: "Read more about "+ b.title, "data-toggle":"tooltip", "data-placement": "bottom" %>
		<small><small class="muted" data-toggle="tooltip" data-placement="bottom" title="<%= title %> has been created on <%= created %> by <%= author %>">[<%= author %>] <%= created %></small></small>
		<blockquote>
			<p data-toggle="popover" data-placement="top" data-content="Click the title to read more about <%= b.title %>"><%= strip_tags(b.contents).first(80) + (strip_tags(b.contents).length > 80 ? "..." : "") %></p>
		</blockquote>
		<%= '<div class="divider"><hr /></div>'.html_safe if !@blog.count.eql?cntBlog %>
	<% end %>
	</div>
</div>

app/views/blog/edit.html.erb
<h3>Update</h3>
<%= render "formBlog" %>

app/views/blog/index.html.erb
<div class="panel panel-default">
	<div class="panel-body">
		<%= render "blog" %>
	</div>
</div>

app/views/blog/new.html.erb
<h3>Create New</h3>
<%= render "formBlog" %>

app/views/blog/read.html.erb
<%
if @blog
title = @blog.title.to_s()
created = @blog.created_at.strftime("%m/%e/%Y at %I:%M %p")
updated = @blog.updated_at.strftime("%m/%e/%Y at %I:%M %p")
author = @blog.author.split("@").first.to_s()
%>
<h3>
	<%= title %>
	<small><small class="muted" data-toggle="tooltip" data-placement="bottom" title="<%= title %> has been created on <%= created %> by <%= author %>">[<%= author %>] <%= created %></small></small>
</h3>
<hr />
<div class="panel panel-default">
	<div class="panel-body text-justify">
		<blockquote><%= @blog.contents.html_safe %></blockquote>
	</div>
	<div class="panel-footer"><small><small class="muted" data-toggle="tooltip" data-placement="bottom" title="<%= title %> has been recently updated on <%= updated %>">Last Updated <%= updated %></small></small></div>
</div>

<div class="panel panel-default">
	<div class="panel-heading">
		<h5 class="panel-title">Comments</h5>
	</div>
	<div class="panel-body">
		<%= render @blog.comments %>
		<%= '<p class="text-danger"><em>Nothing found...</em></p>'.html_safe unless @blog.comments.any? %>
	</div>
	<div class="panel-footer">
		<%= render "comments/formComment" %>
	</div>
</div>
<% end %>

app/views/blog/show.html.erb
<%
title = @blog.title.to_s()
created = @blog.created_at.strftime("%m/%e/%Y at %I:%M %p")
updated = @blog.updated_at.strftime("%m/%e/%Y at %I:%M %p")
%>
<h3>
	<%= title %>
	<small><small class="muted" data-toggle="tooltip" data-placement="bottom" title="<%= title %> has been created on <%= created %>"><%= created %></small></small>
	<small class="pull-right">
		<%= link_to '<span class="glyphicon glyphicon-edit"></span><span class="sr-only">Update</span>'.html_safe, edit_blog_path(@blog), title: "Update #{title}", "data-toggle": "tooltip", "data-placement": "bottom"  %>
		<%= link_to '<span class="glyphicon glyphicon-remove-sign"></span><span class="sr-only">Delete</span></a>'.html_safe, blog_path(@blog), method: :delete, data: { confirm: "Do you really want to delete #{title}?" }, title: "Delete #{title}", "data-toggle": "tooltip", "data-placement": "bottom"  %>
	</small>
</h3>
<hr />
<div class="panel panel-default">
	<div class="panel-body text-justify">
		<blockquote><%= @blog.contents.html_safe %></blockquote>
	</div>
	<div class="panel-footer"><small><small class="muted" data-toggle="tooltip" data-placement="bottom" title="<%= title %> has been recently updated on <%= updated %>">Last Updated <%= updated %></small></small></div>
</div>

<div class="panel panel-default">
	<div class="panel-heading">
		<h5 class="panel-title">Comments</h5>
	</div>
	<div class="panel-body">
		<%= render @blog.comments %>
		<%= '<p class="text-danger"><em>Nothing found...</em></p>'.html_safe unless @blog.comments.any? %>
	</div>
	<div class="panel-footer">
		<%= render "comments/formComment" %>
	</div>
</div>