config/routes.rb
Rails.application.routes.draw do
	# User
	resources :users, only: [:index, :new, :create]
	resources :user_sessions, only: [:create, :destroy]
	resources :password_resets, only: [:new, :create, :edit, :update]
	delete "/sign_out", to: "user_sessions#destroy", as: :sign_out
	get "/sign_in", to: "user_sessions#new", as: :sign_in
	#/User

	# Blog
	post "/blog/all/search", to: "blog#all", as: "search_all"
	get "/blog/all/search", to: "blog#all"
	get "/blog/all", to: "blog#all", as: "all_blog"
	get "/blog/all/:id/read", to: "blog#read", as: "read_blog"
	
	resources :blog do
		resources :comments
	end
	
	post "/blog/search", to: "blog#index", as: "search_blog"
	get "/blog", to: "blog#index", as: "blags"
	get "/blog/:id", to: "blog#update", as: "blag"
	get "/blog", to: "blog#index"
	get "/blog/:id/edit", to: "blog#edit", as: "edit_blag"
	
	get "/blog/:blag_id/comments", to: "comments#index", as: "blag_comments"
	post "/blog/:blag_id/comments", to: "comments#create"
	get "/blog/:blag_id/comments/new", to: "comments#new", as: "new_blag_comment"
	get "/blog/:blag_id/comments/:id/edit", to: "comments#edit", as: "edit_blag_comment"
	get "/blog/:blag_id/comments/:id", to: "comments#show", as: "blag_comment"
	patch "/blog/:blag_id/comments/:id", to: "comments#update"
	put "/blog/:blag_id/comments/:id", to: "comments#update"
	delete "/blog/:blag_id/comments/:id", to: "comments#destroy"
	#/Blog

	# Blog API
	namespace :api, path: "/v1", defaults: { format: :json, constraints: { subdomain: "api" } } do
		resources :blog, only: [:index, :show] do
			resources :comments
		end
	end
	#/Blog API
	
	root "welcome#index"
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
	consecutive_failed_logins_limit 5
	failed_login_ban_for 0
	logout_on_timeout true
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
	skip_before_action :require_login
	
	private def user_session_params
		params.require(:user_session).permit(:email, :password, :remember_me)
	end
	
	def new
		redirect_to users_path unless current_user.blank?
		@user_session = UserSession.new
	end
	
	def create
		@user_session = UserSession.new(user_session_params)
		transact = @user_session.save
		strEmail = @user_session.email.to_s()
		email = " <strong>"+ strEmail +"</strong>" if !strEmail.blank?
		respond_to do |format|
			if transact
				flash[:success] = "Welcome back, <strong>"+ strEmail.split("@").first.to_s() +"</strong>!"
				format.html { redirect_to users_path }
				format.json { render :show, status: :created, location: users_path }
			else
				flash[:danger] = "Unable to sign in"+ email +" because "+ @user_session.errors.to_a.join(", ") +"."
				format.html { redirect_to sign_in_path }
				format.json { render json: @user_session.errors, status: :unprocessable_entity }
			end
		end
	end
	
	def destroy
		strEmail = current_user.email.to_s()
		email = " <strong>"+ strEmail +"</strong>" if !strEmail.blank?
		transact = current_user_session.destroy
		respond_to do |format|
			if transact
				flash[:success] = "Goodbye, <strong>"+ strEmail.split("@").first.to_s() +"</strong>!"
				format.html { redirect_to root_path }
				format.json { render :show, status: :ok, location: root_path }
			else
				flash[:danger] = "Unable to sign out"+ email +" because "+ current_user_session.errors.to_a.join(", ") +"."
				format.html { redirect_to root_path }
				format.json { render json: current_user_session.errors, status: :unprocessable_entity }
			end
		end
	end
end

app/views/user_sessions/new.html.erb
<div class="col-sm-offset-4 col-sm-4">
	<div class="panel panel-primary">
		<div class="panel-heading"><h1 class="panel-title text-center">Sign In</h1></div>
		<div class="panel-body">
			<%= form_for @user_session, html: { class: "form-horizontal" } do |f| %>
				<div class="field form-group">
					<%= f.label :email, class: "control-label sr-only" %>
					<div class="col-sm-12">
					<%= f.email_field :email, class: "form-control", placeholder: "Email", required: "true", title: "Email Address as Username", "data-toggle": "tooltip", "data-placement": "left", autofocus: true %>
					</div>
				</div>
				<div class="field form-group">
					<%= f.label :password, class: "control-label sr-only" %>
					<div class="col-sm-12">
					<%= f.password_field :password, class: "form-control", placeholder: "Password", required: "true", title: "Password", "data-toggle": "tooltip", "data-placement": "left" %>
					</div>
				</div>
				<div class="field form-group">
					<div class="checkbox col-sm-5">
					<label title="Keep me logged in?" data-toggle="tooltip" data-placement="left">
					<%= f.check_box :remember_me %> Keep me?
					</label>
					</div>
					<div class="col-sm-offset-1 col-sm-6" style="margin-top:7px">
					<%= link_to "Forgot Password?", new_password_reset_path, title: "Forgot Password?", "data-toggle": "tooltip", "data-placement": "bottom" %>
					</div>
				</div>
				<div class="actions form-group">
					<h7>&nbsp;</h7>
					<div class="col-sm-12 text-center">
					<%= f.submit "Sign In", class: "btn btn-primary", title: "Sign In", "data-toggle": "tooltip", "data-placement": "bottom" %>
					<%= f.button :Clear, type: "reset", class: "btn btn-default", title: "Clear Above Fields", "data-toggle": "tooltip", "data-placement": "bottom" %>
					</div>
				</div>
			<% end %>
		</div>
	</div>
</div>