config/routes.rb
Rails.application.routes.draw do
	# User
	resources :users, only: [:index, :new, :create]
	resources :user_sessions, only: [:create, :destroy]
	resources :password_resets, only: [:new, :create, :edit, :update]
	delete "/sign_out", to: "user_sessions#destroy", as: :sign_out
	get "/sign_in", to: "user_sessions#new", as: :sign_in
	#/User

	# Blog
	post "/blog/all/search", to: "blog#all", as: "search_all"
	get "/blog/all/search", to: "blog#all"
	get "/blog/all", to: "blog#all", as: "all_blog"
	get "/blog/all/:id/read", to: "blog#read", as: "read_blog"
	
	resources :blog do
		resources :comments
	end
	
	post "/blog/search", to: "blog#index", as: "search_blog"
	get "/blog", to: "blog#index", as: "blags"
	get "/blog/:id", to: "blog#update", as: "blag"
	get "/blog", to: "blog#index"
	get "/blog/:id/edit", to: "blog#edit", as: "edit_blag"
	
	get "/blog/:blag_id/comments", to: "comments#index", as: "blag_comments"
	post "/blog/:blag_id/comments", to: "comments#create"
	get "/blog/:blag_id/comments/new", to: "comments#new", as: "new_blag_comment"
	get "/blog/:blag_id/comments/:id/edit", to: "comments#edit", as: "edit_blag_comment"
	get "/blog/:blag_id/comments/:id", to: "comments#show", as: "blag_comment"
	patch "/blog/:blag_id/comments/:id", to: "comments#update"
	put "/blog/:blag_id/comments/:id", to: "comments#update"
	delete "/blog/:blag_id/comments/:id", to: "comments#destroy"
	#/Blog

	# Blog API
	namespace :api, path: "/v1", defaults: { format: :json, constraints: { subdomain: "api" } } do
		resources :blog, only: [:index, :show] do
			resources :comments
		end
	end
	#/Blog API
	
	root "welcome#index"
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<ul class="nav navbar-nav">
				<li<%= current_page?("/") ? " class=active" : "" %>><%= link_to '&nbsp;<small><span class="glyphicon glyphicon-home"></span><span class="sr-only">Home</span></small>&nbsp;'.html_safe, root_path, class: "navbar-brand", title: "Home", "data-toggle": "tooltip", "data-placement": "bottom" %></li>
			</ul>
		</div>
		<div class="navbar-collapse collapse">
			<ul id="navbar-main" class="nav navbar-nav">
				<li<%= request.original_url[/blog\/all+/] ? " class=active" : "" %>><%= link_to '&nbsp;<span class="glyphicon glyphicon-list-alt"></span><span class="sr-only">All Blog</span>&nbsp;'.html_safe, all_blog_path, title: "All Blog", "data-toggle": "tooltip", "data-placement": "bottom" %></li>
			</ul>
			<% strUser = " ".to_s() + (current_user ? current_user.email.split("@").first : "").to_s() +'&nbsp;<span class="glyphicon glyphicon-user"></span><span class="sr-only">User</span>&nbsp;' %>
			<ul id="navbar-user" class="nav navbar-nav pull-right">
				<li<%= request.original_url[/(user|sign)+/] || (request.original_url[/blog+/] && !request.original_url[/blog\/all+/]) ? " class=active" : "" %> title="User Options" data-toggle="tooltip" data-placement="left">
					<%= link_to strUser.html_safe, "#", class: "dropdown-toggle", "data-toggle": "dropdown", title: "User Options" %>
					<ul class="dropdown-menu navbar-user pull-right" role="menu">
					<% if current_user %>
						<li<%= request.original_url[/blog+/] && !request.original_url[/blog\/all+/] ? " class=active" : "" %>><%= link_to '&nbsp;<span class="glyphicon glyphicon-pencil"></span>&nbsp;My Blog'.html_safe, blog_index_url, title: "My Blog" %></li>
						<li<%= request.original_url[/user/] ? " class=active" : "" %>><%= link_to '&nbsp;<span class="glyphicon glyphicon-user"></span>&nbsp;User Profile'.html_safe, users_path, title: "User Profile" %></li>
						<li><%= link_to '&nbsp;<span class="glyphicon glyphicon-log-out"></span>&nbsp;Sign Out'.html_safe, sign_out_path, method: :delete, title: "Sign Out" %></li>
					<% else %>
						<li<%= request.original_url[/sign\_in/] ? " class=active" : "" %>><%= link_to '<span class="glyphicon glyphicon-log-in"></span>&nbsp;Sign In'.html_safe, sign_in_path, title: "Sign In" %></li>
						<li<%= request.original_url[/users\/new/] ? " class=active" : "" %>><%= link_to '&nbsp;<span class="glyphicon glyphicon-edit"></span>&nbsp;Sign Up'.html_safe, new_user_path, title: "Sign Up" %></li>
					<% end %>
					</ul>
				</li>
			</ul>
			<% if current_user %>
			<ul id="navbar-search" class="nav navbar-nav col-sm-2 pull-right">
				<%= form_tag request.original_url[/blog\/all+/] ? search_all_path : search_blog_path, class: "form-horizontal" do -%>
				<li title="Search <%= request.original_url[/blog\/all+/] ? "All" : "My" %> Blog" data-toggle="tooltip" data-placement="left">
					<div class="input-group" style="margin-top:8px">
						<span class="input-group-addon" id="sizing-addon2"><span class="glyphicon glyphicon-search"></span></span>
						<%= text_field_tag :search, nil, class: "form-control", placeholder: "Search...", "aria-describedby": "sizing-addon2" %>
					</div>
				</li>
				<% end -%>
			</ul>
			<% end %>
		</div>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>K@Blog</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
		<%= render "layouts/navbar" %>
		<div id="main-container" class="container-fluid">
			<div class="row">
				<div class="col-xs-offset-1 col-xs-10">
					<% flash.each do |name, msg| -%>
						<% msg = "<button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></button><span class=\"sr-only\">"+ (name == 'danger' ? 'Error' : 'Success') +":</span><span class=\"glyphicon glyphicon-"+ (name == 'danger' ? 'exclamation' : 'ok') +"-sign\" aria-hidden=\"true\"></span> "+ msg %>
						<%= content_tag :div, msg.html_safe, class: "alert alert-#{name}", role: "alert" %>
					<% end -%>
					<%= yield %>
				</div>
			</div>
		</div>
		<footer class="text-center">
			<div class="divider"><hr /></div>
			<p class="text-muted">&trade; K@Blog &copy; <%= Time.now.year %></p>
		</footer>
</body>
</html>
<% flash.clear %>